name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  merge_group:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      react_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      react_version:
        required: true
        type: string

jobs:
  test:
    name: Test on (Node ${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        version: [24.0.0, 22.12.0, 20.19.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || '' }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: ${{ !inputs.react_version && 'pnpm' || '' }}
      - if: ${{ inputs.react_version }}
        run: |
          yq eval -i '.overrides |= (.react = "${{ inputs.react_version }}" | .["react-dom"] = "${{ inputs.react_version }}" | .["react-server-dom-webpack"] = "${{ inputs.react_version }}")' pnpm-workspace.yaml
          pnpm install --no-frozen-lockfile
      - run: pnpm install
      - run: pnpm run compile
      - run: pnpm test
        env:
          VITE_EXPERIMENTAL_WAKU_ROUTER: true
